--RECOMMANDATIONS
   --ACT_RECO_VALEUR

ALTER TABLE ACT_RECO_VALEUR
ADD loginModif VARCHAR(32) NULL

  --ACT_RECO_SECTOR
ALTER TABLE ACT_RECO_SECTOR
ADD loginModif VARCHAR(32) NULL

ALTER TABLE ACT_RECO_SECTOR
ADD reco_MXEUM VARCHAR(4) NULL

ALTER TABLE ACT_RECO_SECTOR
ADD reco_MXEM VARCHAR(4) NULL

ALTER TABLE ACT_RECO_SECTOR
ADD reco_MXUSLC VARCHAR(4) NULL
   
  

